name: package-order-service

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/order-service/**'
  workflow_call:
    inputs:
        build_number:
          required: true
          type: string
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-order-service:
    
    runs-on: ubuntu-latest

    steps:
          
      - name: Set environment variables
        id: set-variables
        run: |
          echo "REPOSITORY=${{ secrets.ACR_REPO }}/code-to-cloud" >> "$GITHUB_OUTPUT"
          echo "IMAGE=order-service" >> "$GITHUB_OUTPUT"
          echo "VERSION=${{ inputs.build_number }}" >> "$GITHUB_OUTPUT"
          echo "CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: Env variable output
        id: test-variables
        run: |
          echo ${{ steps.set-variables.outputs.REPOSITORY }}
          echo ${{ steps.set-variables.outputs.IMAGE }}
          echo ${{ steps.set-variables.outputs.VERSION }}
          echo ${{ steps.set-variables.outputs.CREATED }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REPO }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}   
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/order-service
          file: src/order-service/Dockerfile
          #platforms: linux/amd64 ,linux/arm64
          platforms: linux/amd64
          push: false
          tags: |
            ${{ steps.set-variables.outputs.REPOSITORY }}/${{ steps.set-variables.outputs.IMAGE }}:latest
            ${{ steps.set-variables.outputs.REPOSITORY }}/${{ steps.set-variables.outputs.IMAGE }}:${{ steps.set-variables.outputs.VERSION }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.created=${{ steps.set-variables.outputs.CREATED }}
            org.opencontainers.image.revision=${{ steps.set-variables.outputs.VERSION }}
            
      - name: Inspect Store Front Image
        run: |
          docker inspect --format='{{index .Id}}' ${{ steps.set-variables.outputs.REPOSITORY }}/${{ steps.set-variables.outputs.IMAGE }}:${{ steps.set-variables.outputs.VERSION }} > ${{ steps.set-variables.outputs.IMAGE }}-digest.txt

      - name: Save Store Front Image
        run: |
          docker save ${{ steps.set-variables.outputs.REPOSITORY }}/${{ steps.set-variables.outputs.IMAGE }}:${{ steps.set-variables.outputs.VERSION }} -o ${{ steps.set-variables.outputs.IMAGE }}.tar
      
      - name: Upload Order Service Image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.set-variables.outputs.IMAGE }}-image
          path: ${{ steps.set-variables.outputs.IMAGE }}.tar

      - name: Upload Order Service Digest
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.set-variables.outputs.IMAGE }}-digest
          path: ${{ steps.set-variables.outputs.IMAGE }}-digest.txt
